image: Visual Studio 2022

configuration:
  - Release

platform:
  - Win32
  - x64

before_build:
  - cmd: git -C .. clone -q https://github.com/MediaArea/zlib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/ZenLib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/MediaInfoLib.git

build:
  project: Project\MSVC2022\CLI\MediaInfo.vcxproj
  verbosity: quiet
