base: core24

name: mediainfo-gui
version: '25.03'
summary: Graphical utility for reading information from audio/video files
description: |
  MediaInfo is a utility used for retrieving technical information and other
  metadata about audio or video files.
license: BSD-2-Clause
contact: info@mediaarea.net
website: https://mediaarea.net/MediaInfo
donation: https://mediaarea.net/MediaInfo/Donate
confinement: strict
grade: stable

lint:
  ignore:
    - classic
    - library:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmms.*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxdot.*

plugs:
  shared-memory:
    private: true

apps:
  mediainfo-gui:
    extensions:
      - kde-neon
    environment:
      GVBINDIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz
      QTWEBENGINE_DISABLE_SANDBOX: 1
    command: usr/bin/mediainfo-gui-wrapper
    plugs:
      - x11
      - unity7
      - wayland
      - opengl
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media

parts:
  mediainfo-gui:
    plugin: qmake
    source: MediaInfo
    qmake-project-file: Project/QMake/GUI/MediaInfoQt.pro
    build-packages:
      - qttools5-dev-tools
      - qtbase5-dev-tools
      - qtwebengine5-dev
      - qtbase5-dev
      - qt5-qmake
      - qtchooser
    stage-packages:
      - libcurl4t64
      - libmms0
      - libcdt5
      - libcgraph6
      - libgvc6
      - libpathplan4
      - libxdot4
      - qtwayland5
      - libqt5svg5
      - libqt5xml5t64
      - libqt5webenginewidgets5
      - xkb-data
    override-build: |
      craftctl default
      cat > $CRAFT_PART_INSTALL/usr/bin/mediainfo-gui-wrapper << 'END'
      #!/bin/sh
      export XKB_CONFIG_ROOT=$SNAP/usr/share/X11/xkb
      exec mediainfo-gui "$@"
      END
      chmod +x $CRAFT_PART_INSTALL/usr/bin/mediainfo-gui-wrapper
    override-prime: |
      craftctl default
      GVBINDIR=$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz $CRAFT_PRIME/usr/sbin/libgvc6-config-update -c
    after:
      - libmediainfo
      - libzen
      - build-essential

  libmediainfo:
    plugin: autotools
    source: MediaInfoLib
    source-subdir: Project/GNU/Library
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
      - --with-graphviz=runtime
      - --with-libcurl
      - --with-libmms
    build-packages:
      - libcurl4-openssl-dev
      - libgraphviz-dev
      - libmms-dev
      - zlib1g-dev
    after:
      - libzen
      - build-essential
    prime:
      - usr/lib/libmediainfo.*

  libzen:
    plugin: autotools
    source: ZenLib
    source-subdir: Project/GNU/Library
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
    after:
      - build-essential
    prime:
      - usr/lib/libzen.*

  build-essential:
    plugin: nil
    build-packages:
      - build-essential
      - pkgconf
