/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// Generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.ui.components

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import androidx.tv.material3.darkColorScheme

/**
 * A section header for TV settings groups.
 * Includes built-in top spacing to visually separate it from the preceding category.
 *
 * @param title The text to display as the category name.
 * @param modifier Modifier for the root [Column].
 */
@Composable
fun CategoryHeader(
    title: String,
    modifier: Modifier = Modifier
) {
    Column(
        modifier = modifier
            .padding(horizontal = 16.dp)
            .padding(top = 24.dp, bottom = 8.dp) // Built-in spacing
    ) {
        Text(
            text = title.uppercase(), // Uppercase often helps distinguish headers on TV
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            letterSpacing = 1.2.sp,
            modifier = Modifier.alpha(0.6f)
        )
    }
}

@Preview(
    name = "Full Screen TV Settings (Dark 4K)",
    device = "id:tv_4k"
)
@Composable
private fun CategoryHeaderDarkPreview() {
    MaterialTheme(colorScheme = darkColorScheme()) {
        Surface(modifier = Modifier.fillMaxSize()) {
            Column {
                CategoryHeader(title = "Network & Internet")

                Text(
                    text = "Wi-Fi: Connected",
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
                    style = MaterialTheme.typography.bodyLarge
                )

                CategoryHeader(title = "System Update")

                Text(
                    text = "Check for updates",
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp),
                    style = MaterialTheme.typography.bodyLarge
                )
            }
        }
    }
}
