/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// Generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.ui.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ChevronLeft
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.onFocusChanged
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.tv.material3.Icon
import androidx.tv.material3.ListItem
import androidx.tv.material3.LocalContentColor
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Text
import androidx.tv.material3.darkColorScheme

/**
 * A TV-optimized settings row that cycles through multiple options.
 *
 * @param label The primary title of the setting.
 * @param options A list of strings representing the available choices.
 * @param selectedIndex The index of the currently active option.
 * @param onOptionChanged Callback triggered with the new index when the user clicks.
 * @param modifier Modifier for the root [ListItem].
 * @param supportingText Optional description string displayed below the label.
 */
@Suppress("LongParameterList")
@Composable
fun MultiOptionListItem(
    label: String,
    options: List<String>,
    selectedIndex: Int,
    onOptionChanged: (Int) -> Unit,
    modifier: Modifier = Modifier,
    supportingText: String? = null
) {
    var isFocused by remember { mutableStateOf(false) }
    ListItem(
        selected = false,
        onClick = {
            val nextIndex = (selectedIndex + 1) % options.size
            onOptionChanged(nextIndex)
        },
        headlineContent = {
            Text(text = label)
        },
        supportingContent = supportingText?.let {
            {
                Text(
                    text = it
                )
            }
        },
        trailingContent = {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                // Use LocalContentColor for the arrows (they will naturally dim/brighten)
                val iconColor = LocalContentColor.current.copy(alpha = 0.6f)

                Icon(
                    imageVector = Icons.Default.ChevronLeft,
                    contentDescription = null,
                    modifier = Modifier.size(20.dp),
                    tint = iconColor
                )

                Text(
                    text = options[selectedIndex],
                    style = MaterialTheme.typography.labelLarge,
                    color = if (isFocused) {
                        MaterialTheme.colorScheme.onPrimary
                    } else {
                        MaterialTheme.colorScheme.primary
                    }
                )

                Icon(
                    imageVector = Icons.Default.ChevronRight,
                    contentDescription = null,
                    modifier = Modifier.size(20.dp),
                    tint = iconColor
                )
            }
        },
        modifier = modifier.onFocusChanged { isFocused = it.isFocused }
    )
}

@Preview(
    name = "MultiOptionListItem 4K Static",
    device = "id:tv_4k",
)
@Composable
private fun MultiOptionListItemStaticPreview() {
    MaterialTheme(colorScheme = darkColorScheme()) {
        Surface(
            modifier = Modifier.fillMaxSize()
        ) {
            Column(
                modifier = Modifier.padding(32.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Example 1: Standard usage
                MultiOptionListItem(
                    label = "Screen Resolution",
                    options = listOf("1080p", "4K (Recommended)", "720p"),
                    selectedIndex = 1,
                    onOptionChanged = {}
                )

                // Example 2: With supporting text
                MultiOptionListItem(
                    label = "Language",
                    options = listOf("English", "Español", "Français"),
                    selectedIndex = 0,
                    onOptionChanged = {},
                    supportingText = "Choose your preferred system language"
                )

                // Example 3: Long labels to check text wrapping/truncation
                MultiOptionListItem(
                    label = "High Dynamic Range (HDR) Display Mode",
                    options = listOf("Always On", "Adaptive", "Off"),
                    selectedIndex = 1,
                    onOptionChanged = {},
                    supportingText = "HDR improves the range of color and contrast"
                )
            }
        }
    }
}
