/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// Generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.ui.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.tv.material3.ListItem
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Surface
import androidx.tv.material3.Switch
import androidx.tv.material3.Text
import androidx.tv.material3.darkColorScheme

/**
 * A specialized list item for TV interfaces that displays a title,
 * description, and a trailing [Switch].
 *
 * This component is optimized for D-pad navigation. By handling the
 * click at the [ListItem] level and setting the Switch's `onCheckedChange`
 * to null, the entire row becomes a single focusable target, preventing
 * "double-focus" issues common on TV platforms.
 *
 * @param title The primary text to be displayed in the headline.
 * @param description The secondary text providing additional context.
 * @param isChecked Whether the switch is currently in the 'on' or 'off' state.
 * @param onToggle Lambda invoked when the list item is clicked,
 * returning the new desired state of the toggle.
 */
@Composable
fun ToggleListItem(
    title: String,
    description: String,
    isChecked: Boolean,
    onToggle: (Boolean) -> Unit
) {
    ListItem(
        selected = false,
        onClick = { onToggle(!isChecked) },
        headlineContent = { Text(title) },
        supportingContent = { Text(description) },
        trailingContent = {
            Switch(
                checked = isChecked,
                onCheckedChange = null // Critical for TV: the Row captures the click
            )
        }
    )
}

@Preview(
    name = "ToggleListItem 4K Gallery",
    device = "id:tv_4k"
)
@Composable
private fun ToggleListItemPreview() {
    MaterialTheme(colorScheme = darkColorScheme()) {
        Surface(
            modifier = Modifier.fillMaxSize()
        ) {
            Column(
                modifier = Modifier.padding(32.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Text(
                    text = "Picture & Inputs",
                    style = MaterialTheme.typography.headlineMedium,
                    modifier = Modifier.padding(bottom = 24.dp)
                )

                // Example 1: Standard TV Toggle
                ToggleListItem(
                    title = "Game Mode",
                    description = "Bypasses post-processing to reduce input lag for consoles.",
                    isChecked = true,
                    onToggle = {}
                )

                // Example 2: HDMI specific setting
                ToggleListItem(
                    title = "HDMI-CEC",
                    description = "Allow the TV to control external devices over HDMI.",
                    isChecked = false,
                    onToggle = {}
                )

                // Example 3: Connectivity/Privacy setting
                ToggleListItem(
                    title = "Wake on LAN",
                    description = "Allows the TV to be turned on from standby via the network.",
                    isChecked = true,
                    onToggle = {}
                )
            }
        }
    }
}
