/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// From code generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.feature.browse

import android.annotation.SuppressLint
import android.content.ContentUris
import android.content.Context
import android.net.Uri
import android.provider.MediaStore
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import net.mediaarea.mediainfo.tv.feature.settings.SortOrder
import kotlin.time.Duration.Companion.seconds

data class MediaItem(
    val id: Long,
    val uri: Uri,
    val name: String,
    val type: MediaType,
    val path: String,
    val dateModified: Long
)

enum class MediaType { Image, Video, Audio }

class MediaRepository(private val context: Context) {

    @SuppressLint("InlinedApi")
    suspend fun fetchMedia(
        sortOrderSetting: SortOrder,
        dispatcher: CoroutineDispatcher = Dispatchers.IO
    ): List<MediaItem> = withContext(dispatcher) {

        val mediaList = mutableListOf<MediaItem>()

        val collection = MediaStore.Files.getContentUri(MediaStore.VOLUME_EXTERNAL)

        val projection = arrayOf(
            MediaStore.Files.FileColumns._ID,
            MediaStore.Files.FileColumns.DISPLAY_NAME,
            MediaStore.Files.FileColumns.MEDIA_TYPE,
            MediaStore.Files.FileColumns.DATA,
            MediaStore.Files.FileColumns.DATE_MODIFIED
        )

        val selection = "${MediaStore.Files.FileColumns.MEDIA_TYPE} IN (?, ?, ?)"
        val selectionArgs = arrayOf(
            MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE.toString(),
            MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO.toString(),
            MediaStore.Files.FileColumns.MEDIA_TYPE_AUDIO.toString()
        )

        val sortOrder = when (sortOrderSetting) {
            SortOrder.DATE -> "${MediaStore.Files.FileColumns.DATE_MODIFIED} DESC"
            SortOrder.PATH -> "${MediaStore.Files.FileColumns.DATA} ASC"
            SortOrder.NAME -> "${MediaStore.Files.FileColumns.DISPLAY_NAME} ASC"
        }

        context.contentResolver.query(
            collection,
            projection,
            selection,
            selectionArgs,
            sortOrder
        )?.use { cursor ->
            val idColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns._ID)
            val nameColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DISPLAY_NAME)
            val typeColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.MEDIA_TYPE)
            val pathColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DATA)
            val dateModifiedColumn =
                cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DATE_MODIFIED)

            while (cursor.moveToNext()) {
                val id = cursor.getLong(idColumn)
                val name = cursor.getString(nameColumn)
                val type = when (cursor.getInt(typeColumn)) {
                    MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO -> MediaType.Video
                    MediaStore.Files.FileColumns.MEDIA_TYPE_AUDIO -> MediaType.Audio
                    else -> MediaType.Image
                }
                val path = cursor.getString(pathColumn)
                val dateModified = cursor.getLong(dateModifiedColumn).seconds.inWholeMilliseconds
                val contentUri = ContentUris.withAppendedId(collection, id)

                mediaList.add(MediaItem(id, contentUri, name, type, path, dateModified))
            }
        }
        mediaList
    }
}
