/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// Generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.feature.browse

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import net.mediaarea.mediainfo.tv.feature.settings.SettingsRepository

class MediaViewModel(
    private val repository: MediaRepository,
    private val settingsRepository: SettingsRepository
) : ViewModel() {

    private var loadJob: Job? = null
    private val _uiState = MutableStateFlow<MediaUiState>(MediaUiState.Loading)
    val uiState: StateFlow<MediaUiState> = _uiState.asStateFlow()

    fun loadMedia() {
        // Check if the job is already active; if so, do nothing
        // Prevent accidental parallel runs that are unnecessary and may cause race conditions
        if (loadJob?.isActive == true) return

        loadJob = viewModelScope.launch {
            _uiState.value = MediaUiState.Loading
            @Suppress("TooGenericExceptionCaught")
            try {
                val items = repository.fetchMedia(settingsRepository.settingsFlow.first().sortOrder)
                if (items.isEmpty()) {
                    _uiState.value = MediaUiState.Empty
                } else {
                    _uiState.value = MediaUiState.Success(items)
                }
            } catch (e: Exception) {
                _uiState.value = MediaUiState.Error(e.message ?: "Unknown Error")
            }
        }
    }
}

sealed class MediaUiState {
    object Loading : MediaUiState()
    object Empty : MediaUiState()
    data class Success(val items: List<MediaItem>) : MediaUiState()
    data class Error(val message: String) : MediaUiState()
}
