/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// From code generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.feature.settings

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

const val FLOW_TIMEOUT = 5000L

class SettingsViewModel(private val repository: SettingsRepository) : ViewModel() {

    val uiState: StateFlow<MediaInfoSettings> = repository.settingsFlow
        .stateIn(
            scope = viewModelScope,
            // WhileSubscribed(5000) keeps the flow active for 5s after the UI stops listening
            // (handles configuration changes like rotation)
            started = SharingStarted.WhileSubscribed(FLOW_TIMEOUT),
            initialValue = MediaInfoSettings(
                darkModeEnabled = true,
                sortOrder = SortOrder.fromKey(null),
                legacyStreamDisplayEnabled = false,
                displayCaptions = DisplayCaptions.fromKey(null)
            )
        )

    fun onEvent(event: SettingsEvent) {
        viewModelScope.launch {
            when (event) {
                is SettingsEvent.CycleSortOrder -> {
                    val allOptions = SortOrder.entries.toTypedArray()
                    val currentIndex = allOptions.indexOf(uiState.value.sortOrder)
                    val nextIndex = (currentIndex + 1) % allOptions.size
                    repository.updateSortOrder(allOptions[nextIndex])
                }

                is SettingsEvent.CycleDisplayCaptions -> {
                    val allOptions = DisplayCaptions.entries.toTypedArray()
                    val currentIndex = allOptions.indexOf(uiState.value.displayCaptions)
                    val nextIndex = (currentIndex + 1) % allOptions.size
                    repository.updateDisplayCaptions(allOptions[nextIndex])
                }

                is SettingsEvent.ToggleDarkMode -> {
                    repository.updateDarkMode(event.enabled)
                }

                is SettingsEvent.ToggleLegacyStreamDisplay -> {
                    repository.updateLegacyStreamDisplay(event.enabled)
                }
            }
        }
    }
}

sealed class SettingsEvent {
    object CycleSortOrder : SettingsEvent()
    object CycleDisplayCaptions : SettingsEvent()
    data class ToggleDarkMode(val enabled: Boolean) : SettingsEvent()
    data class ToggleLegacyStreamDisplay(val enabled: Boolean) : SettingsEvent()
}
