/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// From code generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv.feature.settings

import android.content.Context
import androidx.annotation.StringRes
import androidx.datastore.core.IOException
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.emptyPreferences
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map
import net.mediaarea.mediainfo.tv.R

private val Context.dataStore by preferencesDataStore(name = "settings")

data class MediaInfoSettings(
    val darkModeEnabled: Boolean,
    val legacyStreamDisplayEnabled: Boolean,
    val sortOrder: SortOrder,
    val displayCaptions: DisplayCaptions,
)

enum class SortOrder(val key: String, @get:StringRes val labelRes: Int) {
    DATE("date_modified", R.string.date_modified),
    PATH("file_path", R.string.file_path),
    NAME("file_name", R.string.file_name);

    companion object {
        fun fromKey(key: String?) = entries.find { it.key == key } ?: DATE
    }
}

enum class DisplayCaptions(val key: String, @get:StringRes val labelRes: Int) {
    CONTENT("Content", R.string.display_captions_content),
    COMMAND("Command", R.string.display_captions_command),
    STREAM("Stream", R.string.display_captions_stream);

    companion object {
        fun fromKey(key: String?) = entries.find { it.key == key } ?: COMMAND
    }
}

class SettingsRepository(private val context: Context) {
    private companion object {
        val darkModeKey = booleanPreferencesKey("dark_mode")
        val legacyStreamDisplayKey = booleanPreferencesKey("legacy_stream_display")
        val sortOrderKey = stringPreferencesKey("file_sort_order")
        val displayCaptionsKey = stringPreferencesKey("display_captions")
    }

    val settingsFlow: Flow<MediaInfoSettings> = context.dataStore.data
        .catch { exception ->
            if (exception is IOException) emit(emptyPreferences()) else throw exception
        }
        .map { prefs ->
            MediaInfoSettings(
                darkModeEnabled = prefs[darkModeKey] ?: true,
                legacyStreamDisplayEnabled = prefs[legacyStreamDisplayKey] ?: false,
                sortOrder = SortOrder.fromKey(prefs[sortOrderKey]),
                displayCaptions = DisplayCaptions.fromKey(prefs[displayCaptionsKey])
            )
        }

    suspend fun <T> updateSetting(key: Preferences.Key<T>, value: T) {
        context.dataStore.edit { prefs ->
            prefs[key] = value
        }
    }

    suspend fun updateDarkMode(enabled: Boolean) =
        updateSetting(darkModeKey, enabled)

    suspend fun updateLegacyStreamDisplay(enabled: Boolean) =
        updateSetting(legacyStreamDisplayKey, enabled)

    suspend fun updateSortOrder(sortOrder: SortOrder) =
        updateSetting(sortOrderKey, sortOrder.key)

    suspend fun updateDisplayCaptions(displayCaptions: DisplayCaptions) =
        updateSetting(displayCaptionsKey, displayCaptions.key)
}
