/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// From code generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import net.mediaarea.mediainfo.tv.feature.settings.FLOW_TIMEOUT
import net.mediaarea.mediainfo.tv.feature.settings.SettingsRepository

class MainViewModel(repository: SettingsRepository) : ViewModel() {
    val darkModeEnabled: StateFlow<Boolean> = repository.settingsFlow
        .map { it.darkModeEnabled }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(FLOW_TIMEOUT),
            initialValue = true
        )
}
