/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// From code generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv

import android.app.Application
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import net.mediaarea.mediainfo.tv.feature.browse.MediaRepository
import net.mediaarea.mediainfo.tv.feature.browse.MediaViewModel
import net.mediaarea.mediainfo.tv.feature.report.ReportViewModel
import net.mediaarea.mediainfo.tv.feature.settings.SettingsRepository
import net.mediaarea.mediainfo.tv.feature.settings.SettingsViewModel

class ViewModelFactory(
    private val application: Application,
    private val repository: SettingsRepository
) : ViewModelProvider.Factory {
    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        return when {

            modelClass.isAssignableFrom(MainViewModel::class.java) -> {
                MainViewModel(repository) as T
            }

            modelClass.isAssignableFrom(SettingsViewModel::class.java) -> {
                SettingsViewModel(repository) as T
            }

            modelClass.isAssignableFrom(MediaViewModel::class.java) -> {
                MediaViewModel(MediaRepository(application.applicationContext), repository) as T
            }

            modelClass.isAssignableFrom(ReportViewModel::class.java) -> {
                ReportViewModel(application.contentResolver, repository) as T
            }

            else -> throw IllegalArgumentException("Unknown ViewModel class: ${modelClass.name}")
        }
    }
}
