# MediaInfo
# Copyright (C) 2002-2012 MediaArea.net SARL, Info@MediaArea.net
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http:#www.gnu.org/licenses/>.
#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#! /bin/sh

#-----------------------------------------------------------------------
# $1=OS, $2=Platform, $3=so name, $4=so.0 name, $5=so.0.0.0 name
Release_DLL()
{

#-----------------------------------------------------------------------
# Clean up
test -e MediaInfo_DLL_$1_$2.tar     && rm    MediaInfo_DLL_$1_$2.tar
test -e MediaInfo_DLL_$1_$2.tar.bz2 && rm    MediaInfo_DLL_$1_$2.tar.bz2
test -d MediaInfo_DLL_$1_$2         && rm -r MediaInfo_DLL_$1_$2
mkdir   MediaInfo_DLL_$1_$2

#-----------------------------------------------------------------------
# Copying : so
cp -R ../Project/GNU/Library/.libs/libmediainfo.$3 MediaInfo_DLL_$1_$2/
cp -R ../Project/GNU/Library/.libs/libmediainfo.$4 MediaInfo_DLL_$1_$2/
cp ../Project/GNU/Library/.libs/libmediainfo.$5 MediaInfo_DLL_$1_$2/
cd MediaInfo_DLL_$1_$2
strip libmediainfo.$5
cd ..

#-----------------------------------------------------------------------
# Copying : Information file
cp ../License.html MediaInfo_DLL_$1_$2/
cp ../History_DLL.txt MediaInfo_DLL_$1_$2/History.txt
cp ../Changes.txt MediaInfo_DLL_$1_$2/
cp ReadMe_DLL_$1.txt MediaInfo_DLL_$1_$2/ReadMe.txt

#-----------------------------------------------------------------------
# Copying : Developpers, Documentation
cd ../Source/Doc
doxygen
cd ../../Release
mkdir MediaInfo_DLL_$1_$2/Developpers
cp ../Source/Doc/Documentation.html MediaInfo_DLL_$1_$2/Developpers/
mv ../Doc MediaInfo_DLL_$1_$2/Developpers/

#-----------------------------------------------------------------------
# Copying : Developpers, Source
mkdir -p MediaInfo_DLL_$1_$2/Developpers/Source/Example
cp ../Source/Example/HowToUse* MediaInfo_DLL_$1_$2/Developpers/Source/Example/
mkdir -p MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfo
cp ../Source/MediaInfo/MediaInfo.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfo/
cp ../Source/MediaInfo/MediaInfo_Const.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfo/
cp ../Source/MediaInfo/MediaInfo_Events.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfo/
cp ../Source/MediaInfo/MediaInfoList.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfo/
mkdir -p MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL
cp ../Source/MediaInfoDLL/MediaInfoDLL.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL_Static.h MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL.cs MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL.JNA.java MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL.JNative.java MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL.py MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/
cp ../Source/MediaInfoDLL/MediaInfoDLL3.py MediaInfo_DLL_$1_$2/Developpers/Include/MediaInfoDLL/


#-----------------------------------------------------------------------
# Compressing Archive
mv MediaInfo_DLL_$1_$2 MediaInfoLib
tar jcf MediaInfo_DLL_$1_$2.tar.bz2 MediaInfoLib
mv MediaInfoLib MediaInfo_DLL_$1_$2

#-----------------------------------------------------------------------
# Clean up
rm -r MediaInfo_DLL_$1_$2

}
