#! /bin/sh

#-----------------------------------------------------------------------
# $1=OS, $2=Platform
Release_GUI()
{
#-----------------------------------------------------------------------
# Clean up
test -e MediaInfo_GUI_$1_$2.tar     && rm    MediaInfo_GUI_$1_$2.tar
test -e MediaInfo_GUI_$1_$2.tar.bz2 && rm    MediaInfo_GUI_$1_$2.tar.bz2
test -d MediaInfo_GUI_$1_$2         && rm -r MediaInfo_GUI_$1_$2
mkdir   MediaInfo_GUI_$1_$2

#-----------------------------------------------------------------------
# Copying : Exe
cp ../Project/GNU/GUI/mediainfo_gui MediaInfo_GUI_$1_$2/mediainfo_gui
cd MediaInfo_GUI_$1_$2
strip mediainfo_gui
cd ..

#-----------------------------------------------------------------------
# Copying : Licence files
cp ../Licence.html MediaInfo_GUI_$1_$2/

#-----------------------------------------------------------------------
# Copying : History
cp ../History.GUI.txt MediaInfo_GUI_$1_$2/History.txt

#-----------------------------------------------------------------------
# Copying : Information file
cp ReadMe.$1.txt MediaInfo_GUI_$1_$2/ReadMe.txt

#-----------------------------------------------------------------------
# Compressing Archive
tar jchf MediaInfo_GUI_$1_$2.tar.bz2 MediaInfo_GUI_$1_$2

#-----------------------------------------------------------------------
# Clean up
#if "%1"=="SkipCleanUp" goto SkipCleanUp
#rm -r MediaInfo_GUI_$1_$2
#:SkipCleanUp
}

