#! /bin/sh

#-----------------------------------------------------------------------
# $1=mediainfo Package version,
# $2=libmediainfo Package version,
# $3=libzen Package version,
# $4=,
# $5=,
# $6=,
# $7=Platform, $8=CPU, $9=CPU target
Download_Packages()
{
#-----------------------------------------------------------------------
# Downloading
wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/mediainfo/mediainfo$dash$mediainfov-$1$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv mediainfo$dash$mediainfov-$1$9.$type \
 download/mediainfo/$mediainfov/mediainfo/mediainfo$dash$mediainfov-$destversion$9.$7.$type

wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/mediainfo/mediainfo-gui$dash$mediainfov-$1$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv mediainfo-gui$dash$mediainfov-$1$9.$type \
 download/mediainfo/$mediainfov/mediainfo-gui/mediainfo-gui$dash$mediainfov-$destversion$9.$7.$type

wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/libmediainfo/libmediainfo0$dash$libmediainfov-$2$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv libmediainfo0$dash$libmediainfov-$2$9.$type \
 download/mediainfo/$mediainfov/libmediainfo/libmediainfo0$dash$libmediainfov-$destversion$9.$7.$type

wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/libmediainfo/libmediainfo0-$devext$dash$libmediainfov-$2$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv libmediainfo0-$devext$dash$libmediainfov-$2$9.$type \
 download/mediainfo/$mediainfov/libmediainfo/libmediainfo0-$devext$dash$libmediainfov-$destversion$9.$7.$type

wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/libzen/libzen0$dash$libzenv-$3$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv libzen0$dash$libzenv-$3$9.$type \
 download/mediainfo/$mediainfov/libzen/libzen0$dash$libzenv-$destversion$9.$7.$type

wget https://api.opensuse.org/build/home:Zenitram7573/$7/$8/libzen/libzen0-$devext$dash$libzenv-$3$9.$type \
 --no-check-certificate --http-user=Zenitram7573 --http-passwd=Zen@1tram
mv libzen0-$devext$dash$libzenv-$3$9.$type \
 download/mediainfo/$mediainfov/libzen/libzen0-$devext$dash$libzenv-$destversion$9.$7.$type
}

#-----------------------------------------------------------------------
# $1=MI version, $2=ZL version, $3=Package version
Download_Global()
{
#-----------------------------------------------------------------------
# Clean up
rm download/mediainfo/$mediainfov/*.rpm -rf
rm download/mediainfo/$mediainfov/*.deb -rf
mkdir download/mediainfo/$mediainfov
mkdir download/mediainfo/$mediainfov/mediainfo
mkdir download/mediainfo/$mediainfov/mediainfo-gui
mkdir download/mediainfo/$mediainfov/libmediainfo
mkdir download/mediainfo/$mediainfov/libzen

#-----------------------------------------------------------------------
# Downloading
type="deb"
devext="dev"
dash="_"
Download_Packages 1  1  1  x x x   Debian_4      i586   _i386
Download_Packages 1  1  1  x x x   Debian_4      x86_64 _amd64
Download_Packages 1  1  1  x x x   Debian_5      i586   _i386
Download_Packages 1  1  1  x x x   Debian_5      x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_7.10   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_7.10   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_8.04   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_8.04   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_8.10   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_8.10   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_9.04   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_9.04   x86_64 _amd64

type="rpm"
devext="devel"
dash="-"
Download_Packages $1 $2 $3 x x x   CentOS_4        i586   .i386
Download_Packages $1 $2 $3 x x x   CentOS_4        x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   CentOS_5        i586   .i386
Download_Packages $1 $2 $3 x x x   CentOS_5        x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Fedora_10       i586   .i386
Download_Packages $1 $2 $3 x x x   Fedora_10       x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Fedora_11       i586   .i386
Download_Packages $1 $2 $3 x x x   Fedora_11       x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2008   i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2008   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2009   i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2009   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2009.1 i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2009.1 x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   RHEL_4          i586   .i386
Download_Packages $1 $2 $3 x x x   RHEL_4          x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   RHEL_5          i586   .i386
Download_Packages $1 $2 $3 x x x   RHEL_5          x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.0   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.0   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.1   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.1   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.2   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.2   x86_64 .x86_64
}


mediainfov="0.7.25"
libmediainfov="0.7.25"
libzenv="0.4.9"
destversion="1"

Download_Global 4.1 6.1 4.1
