#! /bin/sh

#-----------------------------------------------------------------------
# $1=mediainfo Package version,
# $2=libmediainfo Package version,
# $3=libzen Package version,
# $4=,
# $5=,
# $6=,
# $7=Platform, $8=CPU, $9=CPU target
Download_Packages()
{
#-----------------------------------------------------------------------
# Downloading
wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/MediaInfo/mediainfo$dash$mediainfov-$1$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv mediainfo$dash$mediainfov-$1$9.$type \
 download/binary/mediainfo/$mediainfov/mediainfo$dash$mediainfov-$destversion$9.$7.$type

wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/MediaInfo/mediainfo-gui$dash$mediainfov-$1$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv mediainfo-gui$dash$mediainfov-$1$9.$type \
 download/binary/mediainfo-gui/$mediainfov/mediainfo-gui$dash$mediainfov-$destversion$9.$7.$type

wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/MediaInfoLib/libmediainfo0$dash$libmediainfov-$2$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv libmediainfo0$dash$libmediainfov-$2$9.$type \
 download/binary/libmediainfo0/$libmediainfov/libmediainfo0$dash$libmediainfov-$destversion$9.$7.$type

wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/MediaInfoLib/libmediainfo0-$devext$dash$libmediainfov-$2$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv libmediainfo0-$devext$dash$libmediainfov-$2$9.$type \
 download/binary/libmediainfo0/$libmediainfov/libmediainfo0-$devext$dash$libmediainfov-$destversion$9.$7.$type

wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/ZenLib/libzen0$dash$libzenv-$3$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv libzen0$dash$libzenv-$3$9.$type \
 download/binary/libzen0/$libzenv/libzen0$dash$libzenv-$destversion$9.$7.$type

wget "https://api.opensuse.org/build/home:MediaArea_net/$7/$8/ZenLib/libzen0-$devext$dash$libzenv-$3$9.$type" \
 --no-check-certificate --http-user=MediaArea_net --http-passwd=xxx
mv libzen0-$devext$dash$libzenv-$3$9.$type \
 download/binary/libzen0/$libzenv/libzen0-$devext$dash$libzenv-$destversion$9.$7.$type
}

#-----------------------------------------------------------------------
# $1=MI version, $2=ZL version, $3=Package version
Download_Global()
{
#-----------------------------------------------------------------------
# Clean up
#rm download/binary/mediainfo/$mediainfov/*.rpm -f
#rm download/binary/mediainfo/$mediainfov/*.deb -f
#rm download/binary/mediainfo-gui/$mediainfov/*.rpm -f
#rm download/binary/mediainfo-gui/$mediainfov/*.deb -f
#rm download/binary/libmediainfo0/$libmediainfov/*.rpm -f
#rm download/binary/libmediainfo0/$libmediainfov/*.deb -f
#rm download/binary/libzen0/$libzen/*.rpm -f
#rm download/binary/libzen0/$libzen/*.deb -f
mkdir download/binary/mediainfo/$mediainfov
mkdir download/binary/mediainfo-gui/$mediainfov
mkdir download/binary/libmediainfo0/$libmediainfov
mkdir download/binary/libzen0/$libzenv/

#-----------------------------------------------------------------------
# Downloading
type="deb"
devext="dev"
dash="_"
Download_Packages 1  1  1  x x x   Debian_4      i586   _i386
Download_Packages 1  1  1  x x x   Debian_4      x86_64 _amd64
Download_Packages 1  1  1  x x x   Debian_5      i586   _i386
Download_Packages 1  1  1  x x x   Debian_5      x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_8.04   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_8.04   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_9.04   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_9.04   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_9.10   i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_9.10   x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_10.04  i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_10.04  x86_64 _amd64
Download_Packages 1  1  1  x x x   Ubuntu_10.10  i586   _i386
Download_Packages 1  1  1  x x x   Ubuntu_10.10  x86_64 _amd64

type="rpm"
devext="devel"
dash="-"
Download_Packages $1 $2 $3 x x x   CentOS_5        i586   .i386
Download_Packages $1 $2 $3 x x x   CentOS_5        x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Fedora_12       i586   .i386
Download_Packages $1 $2 $3 x x x   Fedora_12       x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Fedora_13       i586   .i386
Download_Packages $1 $2 $3 x x x   Fedora_13       x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Fedora_14       i586   .i386
Download_Packages $1 $2 $3 x x x   Fedora_14       x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2008   i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2008   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2009.1 i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2009.1 x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2010   i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2010   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   Mandriva_2010.1 i586   .i586
Download_Packages $1 $2 $3 x x x   Mandriva_2010.1 x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   RHEL_5          i586   .i386
Download_Packages $1 $2 $3 x x x   RHEL_5          x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   RHEL_6          i586   .i386
Download_Packages $1 $2 $3 x x x   RHEL_6          x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   SLE_11          i586   .i586
Download_Packages $1 $2 $3 x x x   SLE_11          x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   SLE_11_SP1      i586   .i586
Download_Packages $1 $2 $3 x x x   SLE_11_SP1      x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.1   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.1   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.2   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.2   x86_64 .x86_64
Download_Packages $1 $2 $3 x x x   openSUSE_11.3   i586   .i586
Download_Packages $1 $2 $3 x x x   openSUSE_11.3   x86_64 .x86_64
}


mediainfov="0.7.38"
libmediainfov="0.7.38"
libzenv="0.4.17"
destversion="1"

Download_Global 1.1 1.1 1.1
